name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: veriT-linux.tar.gz
            asset_name: install.tar.gz
          - os: windows-latest
            artifact_name: mything.exe
            asset_name: mything-windows-amd64
          - os: macos-latest
            artifact_name: mything
            asset_name: mything-macos-amd64

        #platform: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      #- name: Setup C++ environment
      #  uses: kurocha/setup-cpp@v1
      # Runs a single command using the runners shell
      - run: autoreconf -f -i
      - name: configure
        run:  ./configure LFLAGS="--always-interactive" --prefix=./install
      - name: build
        run: make clean && make install
      - run: tar cvf install.tar.gz install    
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
